### ISSUE TITLE
Is this library still working?

### ISSUE THREAD

**Issue by holgersindbaek** [Mashape/analytics-agent-ruby#8]
I need it for my Rails API, but seems like it has been out of maintenance for a while?

Also... is there any way to make this library work without ZeroMQ?

**Comment by ahmadnassri** [comment]
as far as I know, it's no longer maintained, but wait for official confirmation from Mashape team (I am no longer affiliated)

meanwhile, checkout: https://github.com/Mashape/galileo-agent-spec

**Comment by nijikokun** [comment]
Unfortunately this agent does not have a maintainer, we do accept PRs.
